/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2023-06-02 11:02:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/gitOurMine/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/spring-webmvc-5.3.6.jar!/META-INF/spring-form.tld", Long.valueOf(1618279800000L));
    _jspx_dependants.put("jar:file:/C:/gitOurMine/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/spring-webmvc-5.3.6.jar!/META-INF/spring.tld", Long.valueOf(1618279800000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.7.8.jar", Long.valueOf(1683020368730L));
    _jspx_dependants.put("jar:file:/C:/gitOurMine/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/spring-security-taglibs-5.7.8.jar!/META-INF/security.tld", Long.valueOf(1681713972000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1680179226870L));
    _jspx_dependants.put("jar:file:/C:/gitOurMine/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.6.jar", Long.valueOf(1680657671732L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/sweetalert2/sweetalert2.all.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/sweetalert2/sweetalert2.min.css\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    \r\n");
      out.write("    <title>:: My-Task:: Signin</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"#\" type=\"image/x-icon\"> <!-- Favicon-->\r\n");
      out.write("    <!-- project css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/my-task.style.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#signIn{\r\n");
      out.write("\t\twidth: 360px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   \tfunction fnMemberSelect(event){\r\n");
      out.write("   \t\tfor(let op of event.target.options){\r\n");
      out.write("   \t\t\tif(op.selected){\r\n");
      out.write("   \t\t\t\tdocument.loginForm.memberEmail.value = op.dataset.memEmail??\"\";\r\n");
      out.write("   \t\t\t\tdocument.loginForm.memPass.value = op.dataset.memPass??\"\";\r\n");
      out.write("   \t\t\t}\r\n");
      out.write("   \t\t}\t\r\n");
      out.write("   \t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mytask-layout\" class=\"theme-indigo\">\r\n");
      out.write("\r\n");
      out.write("    <!-- main body area -->\r\n");
      out.write("    <div class=\"main p-2 py-3 p-xl-5 \">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Body: Body -->\r\n");
      out.write("        <div class=\"body d-flex p-0 p-xl-5\">\r\n");
      out.write("            <div class=\"container-xxl\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row g-0\">\r\n");
      out.write("                    <div class=\"col-lg-6 d-none d-lg-flex justify-content-center align-items-center rounded-lg auth-h100\">\r\n");
      out.write("                        <div style=\"max-width: 25rem;\">\r\n");
      out.write("                            <div class=\"text-center mb-5\">\r\n");
      out.write("                                 <svg  width=\"4rem\" fill=\"currentColor\" class=\"bi bi-clipboard-check\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path fill-rule=\"evenodd\" d=\"M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z\"/>\r\n");
      out.write("                                    <path d=\"M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z\"/>\r\n");
      out.write("                                    <path d=\"M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z\"/>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-5\">\r\n");
      out.write("                                <h2 class=\"color-900 text-center\">My-Task Let's Management Better</h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Image block -->\r\n");
      out.write("                            <div class=\"\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/login-img.svg\" alt=\"login-img\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 d-flex justify-content-center align-items-center border-0 rounded-lg auth-h100\">\r\n");
      out.write("                        <div class=\"w-100 p-3 p-md-5 card border-0 bg-dark text-light\" style=\"max-width: 32rem;\">\r\n");
      out.write("                            <!-- Form -->\r\n");
      out.write("                            <form method=\"post\" class=\"row g-1 p-3 p-md-4\" name=\"loginForm\">\r\n");
      out.write("                            ");
      if (_jspx_meth_security_005fcsrfInput_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                <div class=\"col-12 text-center mb-1 mb-lg-5\">\r\n");
      out.write("                                    <h1>로그인</h1>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <div class=\"mb-2\">\r\n");
      out.write("                                        <label class=\"form-label\">이메일주소</label>\r\n");
      out.write("                                        <input id = \"memberEmail\" name=\"memberEmail\" type=\"email\" class=\"form-control form-control-lg\" placeholder=\"name@example.com\" required />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <div class=\"mb-2\">\r\n");
      out.write("                                        <div class=\"form-label\">\r\n");
      out.write("                                            <span class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                비밀번호\r\n");
      out.write("                                                <a class=\"text-secondary\" href=\"auth-password-reset.html\">비밀번호찾기</a>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <input id=\"memPass\" name=\"memberPassword\" type=\"password\" class=\"form-control form-control-lg\" placeholder=\"***************\" name=\"memberPassword\" required />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <div class=\"form-check\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                            기억하기\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 text-center mt-4\">\r\n");
      out.write("                                    <input type=\"submit\" value=\"로그인\" class=\"btn btn-lg btn-block btn-light lift text-uppercase\" atl=\"signin\" id=\"signIn\"  />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 text-center mt-4\">\r\n");
      out.write("                                    <span class=\"text-muted\"> 아직 계정을 가지고 있지 않나요? <a href=\"/ourmine/member/memberJoin\" class=\"text-secondary\"> 회원가입 하러가기 </a></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <select class=\"custom-select\" onchange=\"fnMemberSelect(event);\">\r\n");
      out.write("\t\t\t\t\t\t          \t<option>로그인유저 선택</option>\r\n");
      out.write("\t\t\t\t\t\t          \t<option data-mem-email=\"wjdwoghks@naver.com\" data-mem-pass=\"wjdwoghks12!\">상위관리자[ADMIN]</option>\r\n");
      out.write("\t\t\t\t\t\t          \t<option data-mem-email=\"dlwpdls@naver.com\" data-mem-pass=\"wjdwoghks12!\">기업관리자[MANAGER]</option>\r\n");
      out.write("\t\t\t\t\t\t          \t<option data-mem-email=\"djawl@naver.com\" data-mem-pass=\"wjdwoghks12!\">일반회원[MEMBER, COMPANY 1, PROJECT 1]</option>\r\n");
      out.write("\t\t\t\t\t\t          \t<option data-mem-email=\"dlfma10@naver.com\" data-mem-pass=\"wjdwoghks12!\">일반회원[MEMBER, COMPANY 3, PM]</option>\r\n");
      out.write("\t\t\t\t\t\t          \t<option data-mem-email=\"dlfma12@naver.com\" data-mem-pass=\"wjdwoghks12!\">일반회원[MEMBER, COMPANY 3, PL]</option>\r\n");
      out.write("\t\t\t\t\t\t          \t<option data-mem-email=\"dlfma13@naver.com\" data-mem-pass=\"wjdwoghks12!\">일반회원[MEMBER, COMPANY 3, EMPLOYEE]</option>\r\n");
      out.write("\t\t\t\t\t\t          </select>\r\n");
      out.write("                                \r\n");
      out.write("                            </form>\r\n");
      out.write("                            <!-- End Form -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> <!-- End Row -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Core Js -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/libscripts.bundle.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/login.jsp(21,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <script type=\"text/javascript\">\r\n");
          out.write("      window.addEventListener(\"DOMContentLoaded\", function(){\r\n");
          out.write("         Swal.fire({\r\n");
          out.write("              icon: 'error',\r\n");
          out.write("              title: 'Oops...',\r\n");
          out.write("              text: '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\r\n");
          out.write("            })\r\n");
          out.write("      });\r\n");
          out.write("   </script>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fcsrfInput_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:csrfInput
    org.springframework.security.taglibs.csrf.CsrfInputTag _jspx_th_security_005fcsrfInput_005f0 = (org.springframework.security.taglibs.csrf.CsrfInputTag) _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody.get(org.springframework.security.taglibs.csrf.CsrfInputTag.class);
    boolean _jspx_th_security_005fcsrfInput_005f0_reused = false;
    try {
      _jspx_th_security_005fcsrfInput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005fcsrfInput_005f0.setParent(null);
      int _jspx_eval_security_005fcsrfInput_005f0 = _jspx_th_security_005fcsrfInput_005f0.doStartTag();
      if (_jspx_th_security_005fcsrfInput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody.reuse(_jspx_th_security_005fcsrfInput_005f0);
      _jspx_th_security_005fcsrfInput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fcsrfInput_005f0, _jsp_getInstanceManager(), _jspx_th_security_005fcsrfInput_005f0_reused);
    }
    return false;
  }
}
