/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2023-06-02 11:02:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.includee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class headerMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.7.8.jar", Long.valueOf(1683020368730L));
    _jspx_dependants.put("jar:file:/C:/gitOurMine/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/spring-security-taglibs-5.7.8.jar!/META-INF/security.tld", Long.valueOf(1681713972000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1680179226870L));
    _jspx_dependants.put("jar:file:/C:/gitOurMine/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourmine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* CSS */\r\n");
      out.write("    #simple-tree-sidebar {\r\n");
      out.write("        transform: translateX(100%);\r\n");
      out.write("        transition: transform 0.5s ease-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #simple-tree-sidebar.visible {\r\n");
      out.write("        transform: translateX(0);\r\n");
      out.write("    }\r\n");
      out.write("    #simple-tree-sidebar {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        overflow-y: auto;\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-left: 1px solid #ccc;\r\n");
      out.write("        transform: translateX(100%);\r\n");
      out.write("        transition: transform 0.3s ease-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #simple-tree-sidebar.visible {\r\n");
      out.write("        transform: translateX(0);\r\n");
      out.write("    }\r\n");
      out.write("    .folder {\r\n");
      out.write("        border: 1px solid #000;\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .folder-toggle {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .folder-details {\r\n");
      out.write("        display: none; /* 초기에는 감춰져 있습니다. */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .folder.open .folder-details {\r\n");
      out.write("        display: block; /* folder가 open 클래스를 가지면 보입니다. */\r\n");
      out.write("    }\r\n");
      out.write("    .orgchartBtn:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes pulse {\r\n");
      out.write("        0% {\r\n");
      out.write("            background-color: #fff; /* 시작색 */\r\n");
      out.write("        }\r\n");
      out.write("        50% {\r\n");
      out.write("            background-color: orange; /* 중간색 */\r\n");
      out.write("        }\r\n");
      out.write("        100% {\r\n");
      out.write("            background-color: #fff; /* 종료색 */\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    .orange {\r\n");
      out.write("        border-radius: 50%;  /* 동그랗게 만들기 */\r\n");
      out.write("        overflow: hidden;  /* 내부의 모든 요소도 동그랗게 만들기 */\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      if (_jspx_meth_security_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Body: Header -->\r\n");
      out.write("<div class=\"container-xxl\">\r\n");
      out.write("\r\n");
      out.write("    <!-- header rightbar icon -->\r\n");
      out.write("    <div class=\"h-right d-flex align-items-center mr-5 mr-lg-0 order-1\">\r\n");
      out.write("        <div class=\"d-flex\">\r\n");
      out.write("\r\n");
      out.write("            <!-- 채팅 -->\r\n");
      out.write("            <a class=\"nav-link collapsed\" href=\"/ourmine/company/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chat/chat\" title=\"Chat\">\r\n");
      out.write("                <i class=\"icofont-chat fs-5\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- 조직도 --><!-- text-primary : 글자색 -->\r\n");
      out.write("            <a type=\"a\" href=\"/ourmine/company/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/orgchart/orgchartList\" class=\"nav-link collapsed orgchartBtn\" title=\"Organization chart\">\r\n");
      out.write("                <i class=\"icofont-company fs-5\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 알림(종) 아이콘 -->\r\n");
      out.write("        <div class=\"dropdown notifications zindex-popover\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle pulse\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                <i class=\"icofont-alarm fs-5 orange\"></i>\r\n");
      out.write("                <span class=\"pulse-ring\"></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div id=\"notification-icon\">\r\n");
      out.write("                <span class=\"badge\" id=\"notification-badge\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"NotificationsDiv\" class=\"dropdown-menu rounded-lg shadow border-0 dropdown-animation dropdown-menu-sm-end p-0 m-0\">\r\n");
      out.write("                <div class=\"card border-0 w380\">\r\n");
      out.write("                    <div class=\"card-header border-0 p-3\">\r\n");
      out.write("                        <h5 class=\"mb-0 font-weight-light d-flex justify-content-between\">\r\n");
      out.write("                            <span>알림</span>\r\n");
      out.write("                            <span class=\"badge text-white\">11</span>\r\n");
      out.write("                        </h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- 알림 내용 -->\r\n");
      out.write("                    <div class=\"tab-content card-body\">\r\n");
      out.write("                        <div class=\"tab-pane fade show active\">\r\n");
      out.write("                            <ul class=\"list-unstyled list mb-0\">\r\n");
      out.write("                                <li class=\"py-2 mb-1 border-bottom alarmList\">\r\n");
      out.write("\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"card-footer text-center border-top-0\" href=\"#\"> View all notifications</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 프로필 -->\r\n");
      out.write("        <!-- Manager -->\r\n");
      out.write("        ");
      if (_jspx_meth_security_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Member -->\r\n");
      out.write("        ");
      if (_jspx_meth_security_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <!-- 프로필 끝 -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("  <!-- 조직도 트리 형태 -->\r\n");
      out.write("    <div id=\"simple-tree-sidebar\" class=\"sidebar px-4 py-4 py-md-5 me-0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- menu toggler -->\r\n");
      out.write("    <button class=\"navbar-toggler p-0 border-0 menu-toggle order-3\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mainHeader\">\r\n");
      out.write("        <span class=\"fa fa-bars\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <!-- 메인 검색창 -->\r\n");
      out.write("    <div class=\"order-0 col-lg-4 col-md-4 col-sm-12 col-12 mb-3 mb-md-0 \">\r\n");
      out.write("        <div class=\"input-group flex-nowrap input-group-lg\">\r\n");
      out.write("<!--             <button type=\"button\" class=\"input-group-text\" id=\"addon-wrapping\"><i class=\"fa fa-search\"></i></button> -->\r\n");
      out.write("            <input type=\"hidden\" class=\"form-control\" placeholder=\"Search\" aria-label=\"search\" aria-describedby=\"addon-wrapping\">\r\n");
      out.write("<!--             <button type=\"button\" class=\"input-group-text add-member-top\" id=\"addon-wrappingone\" data-bs-toggle=\"modal\" data-bs-target=\"#addUser\"><i class=\"fa fa-plus\"></i></button> -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- 구독 정보 -->\r\n");
      out.write("   ");
      if (_jspx_meth_security_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.8/jstree.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t\theaders['Content-Type'] = 'application/json'\r\n");
      out.write("\t\theaders['accept'] = 'application/json'\r\n");
      out.write("\t\tlet orgchartBtn = document.querySelector('.orgchartBtn');\r\n");
      out.write("\t\tconst sidebar = document.getElementById(\"simple-tree-sidebar\");\r\n");
      out.write("\t\tlet memberImage = document.querySelector('.memberImage');\r\n");
      out.write("\t\tlet memberImage2 = document.querySelector('.memberImage2');\r\n");
      out.write("\t\tlet alarmForm = document.querySelector('#alarmForm');\r\n");
      out.write("\t\tlet alarmTitle = document.querySelector('#alarmTitle');\r\n");
      out.write("\t\tlet alarmWriter = document.querySelector('#alarmWriter');\r\n");
      out.write("\t\tlet alarmDate = document.querySelector('#alarmDate');\r\n");
      out.write("\t\tlet alarmContent = document.querySelector('#alarmContent');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tasync function memberImageList(){\r\n");
      out.write("\t\tawait axios.get('/ourmine/member/memberViewJson',{headers:headers})\r\n");
      out.write("\t\t\t\t.then(resp => {\r\n");
      out.write("\t\t\t\t\tlet data = resp.data;\r\n");
      out.write("\t\t\t\t\tconsole.log('data = ',data)\r\n");
      out.write("\t\t\t\t\tmemberImage.innerHTML = '';\r\n");
      out.write("\t\t\t\t\tmemberImage2.innerHTML = '';\r\n");
      out.write("\t\t\t\t\tlet array = []\r\n");
      out.write("\t\t\t\t\tarray.push(data);\r\n");
      out.write("\t\t\t\t\tarray.map(item => {\r\n");
      out.write("\t\t\t\t\t\tif(item.imageContents === null){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log('이미지없음')\r\n");
      out.write("                            memberImage.innerHTML +=  `<img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/mytask/documentation/assets/images/profile_av.png\" alt=\"profile\">`\r\n");
      out.write("\t\t\t\t\t\t\tmemberImage2.innerHTML += `<img class=\"avatar lg rounded-circle img-thumbnail\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/mytask/documentation/assets/images/profile_av.png\" alt=\"profile\">`\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log('이미지있음')\r\n");
      out.write("\t\t\t\t\t\t\tmemberImage.innerHTML +=  `<img class=\"avatar lg rounded-circle img-thumbnail\" src=\"${item.imageContents}\" alt=\"profile\">`\r\n");
      out.write("\t\t\t\t\t\t\tmemberImage2.innerHTML += `<img class=\"avatar lg rounded-circle img-thumbnail\" src=\"${item.imageContents}\" alt=\"profile\">`\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tmemberImageList();\r\n");
      out.write("\r\n");
      out.write("\t\tlet alarmList = document.querySelector('.alarmList');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("async function alarmListMember(){\r\n");
      out.write("\tawait axios.get('/ourmine/alarm/alarmList',{headers: headers})\r\n");
      out.write("\t\t.then(resp => {\r\n");
      out.write("\t\t\tlet data = resp.data;\r\n");
      out.write("\t\t\tconsole.log(\"알림 리스트\", data)\r\n");
      out.write("\t\t\tlet html = '';\r\n");
      out.write("\t\t\tdata.forEach((item, index) => {\r\n");
      out.write("\t\t\t\thtml += `  <a href=\"javascript:void(0);\" class=\"d-flex\" id=\"item${index}\">\r\n");
      out.write("                        <div class=\"flex-fill ms-2\">\r\n");
      out.write("                            <p class=\"d-flex justify-content-between mb-0 \">\r\n");
      out.write("                                <span class=\"font-weight-bold\">${item.alarmSender}</span>\r\n");
      out.write("                                <small>${item.alarmDate}</small>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <span class=\"\">${item.alarmContent}<span class=\"badge bg-success\">Review<span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>`\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\talarmList.innerHTML = html;\r\n");
      out.write("\t\t\tdata.forEach((item, index) => {\r\n");
      out.write("\t\t\t\t// 각 아이템에 클릭 이벤트 리스너를 추가\r\n");
      out.write("\t\t\t\tdocument.getElementById(`item${index}`).addEventListener('click', () => modelView(item));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})\r\n");
      out.write("}\r\n");
      out.write("\t\talarmListMember();\r\n");
      out.write("\t\theaders['accept'] = 'application/json';\r\n");
      out.write("\t\theaders['Content-Type'] = 'application/json'\r\n");
      out.write("\r\n");
      out.write("\t\torgchartBtn.addEventListener('click', () => {\r\n");
      out.write("\t\t\tlet simpleTreeSidebar = $(\"#simple-tree-sidebar\");\r\n");
      out.write("\t\t\tif (simpleTreeSidebar.hasClass(\"visible\")) {\r\n");
      out.write("\t\t\t\tsimpleTreeSidebar.removeClass(\"visible\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\taxios.get(`/ourmine/company/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/orgchart/orgchartTreeJson`, { headers: headers })\r\n");
      out.write("\t\t\t\t\t.then(resp => {\r\n");
      out.write("\t\t\t\t\t\tlet data = resp.data;\r\n");
      out.write("\t\t\t\t\t\tconsole.log('트리 데이터', data);\r\n");
      out.write("\t\t\t\t\t\tupdateSidebar(data);\r\n");
      out.write("\t\t\t\t\t\tsimpleTreeSidebar.addClass(\"visible\");\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction createHierarchy(data, parentId) {\r\n");
      out.write("\t\t\treturn data\r\n");
      out.write("\t\t\t\t.filter(item => item.seniorDepartmentId === parentId)\r\n");
      out.write("\t\t\t\t.map(item => ({\r\n");
      out.write("\t\t\t\t\ttitle: `부서 이름: $\\{item.departmentName}`,\r\n");
      out.write("\t\t\t\t\tkey: item.orgchartId,\r\n");
      out.write("\t\t\t\t\tchildren: createHierarchy(data, item.orgchartId),\r\n");
      out.write("\t\t\t\t\tdepartmentCreateDate: item.departmentCreateDate,\r\n");
      out.write("\t\t\t\t\tmemberId: item.memberId === null ? 'None' : item.memberId\r\n");
      out.write("\t\t\t\t}));\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction updateSidebar(data) {\r\n");
      out.write("\t\t\tlet simpleTreeSidebar = $(\"#simple-tree-sidebar\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet hierarchy = createHierarchy(data, null);\r\n");
      out.write("\t\t\tsimpleTreeSidebar.fancytree({\r\n");
      out.write("\t\t\t\textensions: [\"table\"],\r\n");
      out.write("\t\t\t\tcheckbox: true,\r\n");
      out.write("\t\t\t\tselectMode: 2,\r\n");
      out.write("\t\t\t\tsource: hierarchy,\r\n");
      out.write("\t\t\t\ttable: {\r\n");
      out.write("\t\t\t\t\tcheckboxColumnIdx: 0,\r\n");
      out.write("\t\t\t\t\tnodeColumnIdx: 1\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\trenderColumns: function (event, data) {\r\n");
      out.write("\t\t\t\t\tlet node = data.node,\r\n");
      out.write("\t\t\t\t\t\t$tdList = $(node.tr).find(\">td\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$tdList.eq(2).text(`부서 생성 날짜: ${node.data.departmentCreateDate}`);\r\n");
      out.write("\t\t\t\t\t$tdList.eq(3).text(`회원 ID: ${node.data.memberId}`);\r\n");
      out.write("\t\t\t\t\t$tdList.eq(4).text(`조직도 ID: ${node.key}`);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t// 웹소켓 서버에 연결\r\n");
      out.write("\t\tlet socket = new WebSocket('ws://localhost/ourmine/aws/echo');\r\n");
      out.write("\r\n");
      out.write("\t\t// 연결이 열리면 서버에 메시지를 보낼 수 있습니다.\r\n");
      out.write("\t\tsocket.onopen = function(event) {\r\n");
      out.write("\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t// 서버로부터 메시지를 받으면 이 함수가 호출됩니다.\r\n");
      out.write("\t\tlet orange = document.querySelector('.orange');\r\n");
      out.write("\r\n");
      out.write("\t\torange.addEventListener('click', function() {\r\n");
      out.write("\t\t\tthis.style.animation = '';\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tfunction modelView(item){\r\n");
      out.write("\t\t\tconsole.log(\"modelView Item, \",item);\r\n");
      out.write("            alarmTitle.value = item.alarmContent;\r\n");
      out.write("\t\t\talarmDate.value = item.alarmDate;\r\n");
      out.write("\t\t\talarmWriter.value = item.alarmSender;\r\n");
      out.write("\t\t\tlet modalElement = document.getElementById('modifyModal');\r\n");
      out.write("\t\t\tlet modalInstance = new bootstrap.Modal(modalElement);\r\n");
      out.write("\t\t\tmodalInstance.show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tsocket.onmessage = function(e) {\r\n");
      out.write("\t\t\tlet receivedData = JSON.parse(e.data);\r\n");
      out.write("\t\t\tconsole.log(\"receivedData = \",receivedData)\r\n");
      out.write("\t\t\torange.style.animation = \"pulse 1s infinite\";\r\n");
      out.write("\t\t\tlet message = JSON.parse(receivedData.message);\r\n");
      out.write("\t\t\tlet alarm = [];\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet time = message.time;\r\n");
      out.write("\t\t\tconsole.log(\"time = \",time)\r\n");
      out.write("\t\t\talarm.push(\"message\", message);\r\n");
      out.write("\t\t\talarm.shift();\r\n");
      out.write("\t\t\tconsole.log(\"alarm = \", alarm)\r\n");
      out.write("\t\t\talarm.map(item => {\r\n");
      out.write("\t\t\treturn \talarmList.innerHTML +=  `\r\n");
      out.write("                    <a href=\"javascript:void(0);\" class=\"d-flex\">\r\n");
      out.write("                        <div class=\"flex-\r\n");
      out.write("                        fill ms-2\">\r\n");
      out.write("                            <p class=\"d-flex justify-content-between mb-0 \">\r\n");
      out.write("                                <span class=\"font-weight-bold\">${item.sander}</span>\r\n");
      out.write("                                <small>${item.time}</small>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <span class=\"\">${item.message}<span class=\"badge bg-success\">Review</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>`;\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// 연결이 닫히거나 에러가 발생하면 이 함수가 호출됩니다.\r\n");
      out.write("\t\tsocket.onerror = function(error) {\r\n");
      out.write("\t\t\tconsole.log('WebSocket Error: ', error);\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tsocket.onclose = function(event) {\r\n");
      out.write("\t\t\tconsole.log('WebSocket connection closed: ', event.code);\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_security_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f0.setParent(null);
      // /includee/headerMenu.jsp(70,0) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f0.setProperty("principal");
      // /includee/headerMenu.jsp(70,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f0.setVar("principal");
      int _jspx_eval_security_005fauthentication_005f0 = _jspx_th_security_005fauthentication_005f0.doStartTag();
      if (_jspx_th_security_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f0);
      _jspx_th_security_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /includee/headerMenu.jsp(72,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("companyId");
      // /includee/headerMenu.jsp(72,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/includee/headerMenu.jsp(72,0) '${principal.realUser.companyId}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${principal.realUser.companyId}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("   ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /includee/headerMenu.jsp(74,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyId eq 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <script>\r\n");
          out.write("          const companyId1 = undefined;\r\n");
          out.write("          console.log(\"companyId1 =\",companyId1)\r\n");
          out.write("       </script>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <script>\r\n");
          out.write("         const companyId1 = ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${companyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(";\r\n");
          out.write("         console.log(\"companyId1 =\",companyId1)\r\n");
          out.write("      </script>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_security_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_security_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_security_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthorize_005f0.setParent(null);
      // /includee/headerMenu.jsp(144,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthorize_005f0.setAccess("hasRole('MANAGER')");
      int _jspx_eval_security_005fauthorize_005f0 = _jspx_th_security_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_security_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("        ");
        if (_jspx_meth_security_005fauthentication_005f1(_jspx_th_security_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        <div class=\"dropdown user-profile ml-2 ml-sm-3 d-flex align-items-center zindex-popover\">\r\n");
        out.write("            <div class=\"u-info me-2\">\r\n");
        out.write("                <p class=\"mb-0 text-end line-height-sm \"><span class=\"font-weight-bold\">");
        if (_jspx_meth_security_005fauthentication_005f2(_jspx_th_security_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("</span></p>\r\n");
        out.write("\r\n");
        out.write("               <small style=\"color: orange;\">");
        if (_jspx_meth_security_005fauthentication_005f3(_jspx_th_security_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write(",\r\n");
        out.write("                                ");
        if (_jspx_meth_security_005fauthentication_005f4(_jspx_th_security_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("</small>\r\n");
        out.write("            </div>\r\n");
        out.write("            <a class=\"nav-link dropdown-toggle pulse p-0 memberImage\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" data-bs-display=\"static\">\r\n");
        out.write("\r\n");
        out.write("            </a>\r\n");
        out.write("\r\n");
        out.write("            <div class=\"dropdown-menu rounded-lg shadow border-0 dropdown-animation dropdown-menu-end p-0 m-0\">\r\n");
        out.write("                <div class=\"card border-0 w280\">\r\n");
        out.write("                    <div class=\"card-body pb-0\">\r\n");
        out.write("                        <div class=\"d-flex py-1\">\r\n");
        out.write("                        <span class=\"memberImage2\"></span>\r\n");
        out.write("                            ");
        out.write("\r\n");
        out.write("                            <div class=\"flex-fill ms-3\">\r\n");
        out.write("                                <p class=\"mb-0\"><span class=\"font-weight-bold\">");
        if (_jspx_meth_security_005fauthentication_005f5(_jspx_th_security_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("</span></p>\r\n");
        out.write("                                <small class=\"\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authMember.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</small>\r\n");
        out.write("                            </div>\r\n");
        out.write("                        </div>\r\n");
        out.write("\r\n");
        out.write("                        <div><hr class=\"dropdown-divider border-dark\"></div>\r\n");
        out.write("                    </div>\r\n");
        out.write("                    <div class=\"list-group m-2 \">\r\n");
        out.write("                        <a href=\"/ourmine/project/projectList\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-home fs-6 me-3\"></i>프로젝트</a>\r\n");
        out.write("                        <a href=\"/ourmine/member/memberList\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-tasks fs-5 me-3\"></i>직원관리</a>\r\n");
        out.write("                        <a href=\"/ourmine/member/memberView\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-user-alt-3 fs-5 me-3\"></i>MyPage</a>\r\n");
        out.write("                        <a href=\"\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-users-alt-5 fs-5 me-3\"></i>회사 인원 추가하기</a>\r\n");
        out.write("                  <form id=\"logoutForm\" action=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/logout\" method=\"post\">\r\n");
        out.write("                        ");
        if (_jspx_meth_security_005fcsrfInput_005f0(_jspx_th_security_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                        </form>\r\n");
        out.write("                        <a href=\"javascript:$('#logoutForm').submit();\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-logout fs-6 me-3\"></i>로그아웃</a>\r\n");
        out.write("                    </div>\r\n");
        out.write("                </div>\r\n");
        out.write("            </div>\r\n");
        out.write("        </div>\r\n");
        out.write("        ");
      }
      if (_jspx_th_security_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f0);
      _jspx_th_security_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_security_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f0);
      // /includee/headerMenu.jsp(145,8) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f1.setProperty("principal");
      // /includee/headerMenu.jsp(145,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f1.setVar("authMember");
      int _jspx_eval_security_005fauthentication_005f1 = _jspx_th_security_005fauthentication_005f1.doStartTag();
      if (_jspx_th_security_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f1);
      _jspx_th_security_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f2 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f2_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f2.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f0);
      // /includee/headerMenu.jsp(148,88) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f2.setProperty("principal.realUser.memberName");
      int _jspx_eval_security_005fauthentication_005f2 = _jspx_th_security_005fauthentication_005f2.doStartTag();
      if (_jspx_th_security_005fauthentication_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f2);
      _jspx_th_security_005fauthentication_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f2, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f3 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f3_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f3.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f0);
      // /includee/headerMenu.jsp(150,45) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f3.setProperty("principal.realUser.companyName");
      int _jspx_eval_security_005fauthentication_005f3 = _jspx_th_security_005fauthentication_005f3.doStartTag();
      if (_jspx_th_security_005fauthentication_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f3);
      _jspx_th_security_005fauthentication_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f3, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f4 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f4_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f4.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f0);
      // /includee/headerMenu.jsp(151,32) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f4.setProperty("principal.realUser.memberGrade");
      int _jspx_eval_security_005fauthentication_005f4 = _jspx_th_security_005fauthentication_005f4.doStartTag();
      if (_jspx_th_security_005fauthentication_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f4);
      _jspx_th_security_005fauthentication_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f4, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f5 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f5_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f5.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f0);
      // /includee/headerMenu.jsp(164,79) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f5.setProperty("principal.realUser.memberName");
      int _jspx_eval_security_005fauthentication_005f5 = _jspx_th_security_005fauthentication_005f5.doStartTag();
      if (_jspx_th_security_005fauthentication_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f5);
      _jspx_th_security_005fauthentication_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f5, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fcsrfInput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:csrfInput
    org.springframework.security.taglibs.csrf.CsrfInputTag _jspx_th_security_005fcsrfInput_005f0 = (org.springframework.security.taglibs.csrf.CsrfInputTag) _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody.get(org.springframework.security.taglibs.csrf.CsrfInputTag.class);
    boolean _jspx_th_security_005fcsrfInput_005f0_reused = false;
    try {
      _jspx_th_security_005fcsrfInput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005fcsrfInput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f0);
      int _jspx_eval_security_005fcsrfInput_005f0 = _jspx_th_security_005fcsrfInput_005f0.doStartTag();
      if (_jspx_th_security_005fcsrfInput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody.reuse(_jspx_th_security_005fcsrfInput_005f0);
      _jspx_th_security_005fcsrfInput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fcsrfInput_005f0, _jsp_getInstanceManager(), _jspx_th_security_005fcsrfInput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_security_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_security_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_security_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthorize_005f1.setParent(null);
      // /includee/headerMenu.jsp(187,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthorize_005f1.setAccess("hasRole('MEMBER')");
      int _jspx_eval_security_005fauthorize_005f1 = _jspx_th_security_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_security_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\r');
        out.write('\n');
        out.write("\r\n");
        out.write("        ");
        if (_jspx_meth_security_005fauthentication_005f6(_jspx_th_security_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        <div class=\"dropdown user-profile ml-2 ml-sm-3 d-flex align-items-center zindex-popover\">\r\n");
        out.write("            <div class=\"u-info me-2\">\r\n");
        out.write("                <p class=\"mb-0 text-end line-height-sm \"><span class=\"font-weight-bold\">");
        if (_jspx_meth_security_005fauthentication_005f7(_jspx_th_security_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("</span></p>\r\n");
        out.write("\r\n");
        out.write("               <small style=\"color: orange;\">\r\n");
        out.write("\r\n");
        out.write("               <!-- 회사정보 유무 확인 후 메뉴 출력 -->\r\n");
        out.write("               ");
        if (_jspx_meth_c_005fset_005f1(_jspx_th_security_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("               ");
        if (_jspx_meth_c_005fchoose_005f1(_jspx_th_security_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t       ");
        if (_jspx_meth_security_005fauthentication_005f9(_jspx_th_security_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("               </small>\r\n");
        out.write("            </div>\r\n");
        out.write("            <a class=\"nav-link dropdown-toggle pulse p-0 memberImage\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" data-bs-display=\"static\">\r\n");
        out.write("\r\n");
        out.write("            </a>\r\n");
        out.write("\r\n");
        out.write("            <div class=\"dropdown-menu rounded-lg shadow border-0 dropdown-animation dropdown-menu-end p-0 m-0\">\r\n");
        out.write("                <div class=\"card border-0 w280\">\r\n");
        out.write("                    <div class=\"card-body pb-0\">\r\n");
        out.write("                        <div class=\"d-flex py-1\">\r\n");
        out.write("                            <span class=\"memberImage2\"></span>\r\n");
        out.write("                           ");
        out.write("\r\n");
        out.write("                            <div class=\"flex-fill ms-3\">\r\n");
        out.write("                                <p class=\"mb-0\"><span class=\"font-weight-bold\">");
        if (_jspx_meth_security_005fauthentication_005f10(_jspx_th_security_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("</span></p>\r\n");
        out.write("                                <small class=\"\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authMember.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</small>\r\n");
        out.write("                            </div>\r\n");
        out.write("                        </div>\r\n");
        out.write("\r\n");
        out.write("                        <div><hr class=\"dropdown-divider border-dark\"></div>\r\n");
        out.write("                    </div>\r\n");
        out.write("                    <div class=\"list-group m-2 \">\r\n");
        out.write("                        <a href=\"projects.html\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-home fs-6 me-3\"></i>프로젝트</a>\r\n");
        out.write("                        <a href=\"/task.html\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-tasks fs-5 me-3\"></i>작업</a>\r\n");
        out.write("                        <a href=\"/ourmine/member/memberView\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-user-alt-3 fs-5 me-3\"></i>MyPage</a>\r\n");
        out.write("\t               \t\t\t");
        if (_jspx_meth_c_005fif_005f0(_jspx_th_security_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                        <form id=\"logoutForm\" action=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/logout\" method=\"post\">\r\n");
        out.write("                        ");
        if (_jspx_meth_security_005fcsrfInput_005f1(_jspx_th_security_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                        </form>\r\n");
        out.write("                        <a href=\"javascript:$('#logoutForm').submit();\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-logout fs-6 me-3\"></i>로그아웃</a>\r\n");
        out.write("<!--                         <a href=\"ui-elements/auth-signin.html\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-logout fs-6 me-3\"></i>로그아웃</a> -->\r\n");
        out.write("                    </div>\r\n");
        out.write("                </div>\r\n");
        out.write("            </div>\r\n");
        out.write("        </div>\r\n");
        out.write("\r\n");
        out.write("            <!-- 상세모달 -->\r\n");
        out.write("            <form id=\"alarmForm\" enctype=\"multipart/form-data\" method=\"post\">\r\n");
        out.write("                <div class=\"modal\" id=\"modifyModal\" >\r\n");
        out.write("                    <div class=\"modal-dialog\">\r\n");
        out.write("                        <div class=\"modal-content card mb-3\" id=\"modifyContent\">\r\n");
        out.write("                            <div class=\"card-body\">\r\n");
        out.write("                                <div class=\"row g-3 align-items-center\">\r\n");
        out.write("                                    <div class=\"col-md-12\">\r\n");
        out.write("                                        <div class=\"form-group\">\r\n");
        out.write("                                            <label>제목</label>\r\n");
        out.write("                                            <input type=\"text\" id=\"alarmTitle\" name=\"noticeBoardTitle\" class=\"myModal-title form-control\">\r\n");
        out.write("                                        </div>\r\n");
        out.write("                                    </div>\r\n");
        out.write("\r\n");
        out.write("                                    <div class=\"col-md-12\">\r\n");
        out.write("                                        <div class=\"form-group\">\r\n");
        out.write("                                            <label>보낸이</label>\r\n");
        out.write("                                            <input type=\"text\" id=\"alarmWriter\" name=\"noticeBoardWriter\" class=\"form-control\" readonly>\r\n");
        out.write("                                        </div>\r\n");
        out.write("                                    </div>\r\n");
        out.write("                                    <div class=\"col-md-12\">\r\n");
        out.write("                                        <div class=\"form-group\">\r\n");
        out.write("                                            <label>작성일자</label>\r\n");
        out.write("                                            <input type=\"text\" id=\"alarmDate\" name=\"noticeBoardWriteDate\" class=\"form-control\" readonly>\r\n");
        out.write("                                        </div>\r\n");
        out.write("                                    </div>\r\n");
        out.write("                                </div>\r\n");
        out.write("                                <div class=\"modal-footer\">\r\n");
        out.write("                                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">닫기</button>\r\n");
        out.write("                                </div>\r\n");
        out.write("                            </div>\r\n");
        out.write("                        </div>\r\n");
        out.write("                    </div>\r\n");
        out.write("                </div>\r\n");
        out.write("            </form>\r\n");
        out.write("        ");
      }
      if (_jspx_th_security_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f1);
      _jspx_th_security_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_security_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f6 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f6_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f6.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f1);
      // /includee/headerMenu.jsp(189,8) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f6.setProperty("principal");
      // /includee/headerMenu.jsp(189,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f6.setVar("authMember");
      int _jspx_eval_security_005fauthentication_005f6 = _jspx_th_security_005fauthentication_005f6.doStartTag();
      if (_jspx_th_security_005fauthentication_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f6);
      _jspx_th_security_005fauthentication_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f6, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f7 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f7_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f7.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f1);
      // /includee/headerMenu.jsp(192,88) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f7.setProperty("principal.realUser.memberName");
      int _jspx_eval_security_005fauthentication_005f7 = _jspx_th_security_005fauthentication_005f7.doStartTag();
      if (_jspx_th_security_005fauthentication_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f7);
      _jspx_th_security_005fauthentication_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f7, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f1);
      // /includee/headerMenu.jsp(197,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("companyName");
      // /includee/headerMenu.jsp(197,15) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/includee/headerMenu.jsp(197,15) '${principal.realUser.companyName }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${principal.realUser.companyName }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f1);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t               ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t               ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("               ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /includee/headerMenu.jsp(199,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty companyName}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t               ");
          if (_jspx_meth_security_005fauthentication_005f8(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
            return true;
          out.write(",\r\n");
          out.write("\t               ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f8 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f8_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f8.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      // /includee/headerMenu.jsp(200,17) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f8.setProperty("principal.realUser.companyName");
      int _jspx_eval_security_005fauthentication_005f8 = _jspx_th_security_005fauthentication_005f8.doStartTag();
      if (_jspx_th_security_005fauthentication_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f8);
      _jspx_th_security_005fauthentication_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f8, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                  회사정보가 없습니다.\r\n");
          out.write("\t               ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f9 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f9_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f9.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f1);
      // /includee/headerMenu.jsp(206,9) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f9.setProperty("principal.realUser.memberGrade");
      int _jspx_eval_security_005fauthentication_005f9 = _jspx_th_security_005fauthentication_005f9.doStartTag();
      if (_jspx_th_security_005fauthentication_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f9);
      _jspx_th_security_005fauthentication_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f9, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f10 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f10_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f10.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f1);
      // /includee/headerMenu.jsp(220,79) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f10.setProperty("principal.realUser.memberName");
      int _jspx_eval_security_005fauthentication_005f10 = _jspx_th_security_005fauthentication_005f10.doStartTag();
      if (_jspx_th_security_005fauthentication_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f10);
      _jspx_th_security_005fauthentication_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f10, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f1);
      // /includee/headerMenu.jsp(231,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty companyName}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t                        <a href=\"/ourmine/company/companyListJoin\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-contact-add fs-5 me-3\"></i>회사 가입하기</a>\r\n");
          out.write("\t               \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fcsrfInput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:csrfInput
    org.springframework.security.taglibs.csrf.CsrfInputTag _jspx_th_security_005fcsrfInput_005f1 = (org.springframework.security.taglibs.csrf.CsrfInputTag) _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody.get(org.springframework.security.taglibs.csrf.CsrfInputTag.class);
    boolean _jspx_th_security_005fcsrfInput_005f1_reused = false;
    try {
      _jspx_th_security_005fcsrfInput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_security_005fcsrfInput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f1);
      int _jspx_eval_security_005fcsrfInput_005f1 = _jspx_th_security_005fcsrfInput_005f1.doStartTag();
      if (_jspx_th_security_005fcsrfInput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fcsrfInput_005fnobody.reuse(_jspx_th_security_005fcsrfInput_005f1);
      _jspx_th_security_005fcsrfInput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fcsrfInput_005f1, _jsp_getInstanceManager(), _jspx_th_security_005fcsrfInput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_security_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_security_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_security_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthorize_005f2.setParent(null);
      // /includee/headerMenu.jsp(304,3) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthorize_005f2.setAccess("hasRole('MANAGER')");
      int _jspx_eval_security_005fauthorize_005f2 = _jspx_th_security_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_security_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("   <div class=\"logo-text\" style=\"text-align: center;\">\r\n");
        out.write("    ");
        if (_jspx_meth_security_005fauthentication_005f11(_jspx_th_security_005fauthorize_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    (남은 구독 일자 :\r\n");
        out.write("    ");
        if (_jspx_meth_security_005fauthentication_005f12(_jspx_th_security_005fauthorize_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    일)\r\n");
        out.write("\r\n");
        out.write("    구독 중 <a class=\"ms-link active\" href=\"/ourmine/subscribe/itemList.do\"><span> / 결제하기</span></a>\r\n");
        out.write("    </div>\r\n");
        out.write("    ");
      }
      if (_jspx_th_security_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f2);
      _jspx_th_security_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_security_005fauthorize_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f11 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f11_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f11.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f2);
      // /includee/headerMenu.jsp(306,4) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f11.setProperty("principal.realUser.memberName");
      int _jspx_eval_security_005fauthentication_005f11 = _jspx_th_security_005fauthentication_005f11.doStartTag();
      if (_jspx_th_security_005fauthentication_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f11);
      _jspx_th_security_005fauthentication_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f11, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_security_005fauthorize_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f12 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f12_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f12.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_security_005fauthorize_005f2);
      // /includee/headerMenu.jsp(308,4) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f12.setProperty("principal.realUser.subscribeDate");
      int _jspx_eval_security_005fauthentication_005f12 = _jspx_th_security_005fauthentication_005f12.doStartTag();
      if (_jspx_th_security_005fauthentication_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f12);
      _jspx_th_security_005fauthentication_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f12, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f12_reused);
    }
    return false;
  }
}
